export const from = document.getElementById('from')
export const to = document.getElementById('to')
export const button = document.getElementById('convertBtn')
export const result = document.getElementById('result')
export const amount = document.getElementById('amount') 
